/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animalfriendconnector;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author kingm
 */
public class Beginning extends javax.swing.JFrame {

    /**
     * Creates new form Beginning
     */
    
    //server=0, client=1
    boolean isServer=true;

    public boolean isIsServer() {
        return isServer;
    }

    public void setIsServer(boolean isServer) {
        this.isServer = isServer;
    }
    private int counter=0;
    boolean started=false;
    
    public Beginning() {
        initComponents();
        counter=0;
        accordingToCounter();
        AnimalListCreator.CREATE_LIST();
    }
    private void setIcon(JLabel label, String s,int w, int h)
    {
        
        label.setIcon(new ImageIcon(((new ImageIcon(
            s).getImage()
            .getScaledInstance(w, h,
                    java.awt.Image.SCALE_SMOOTH)))));
    }
    public void accordingToCounter(){
        if(getCounter()==0)
        {
            setIcon(image, "Assets/images/breakTime.png",1400,900);
        }
        else if(getCounter()==1)
        {
            setIcon(image, "Assets/images/callTime.png",1400,900);
        }
        else if(getCounter()==2)
        {
            setIcon(image, "Assets/images/letsGo.png",1400,900);
        }
        else if(getCounter()<1000)
        {
            if(!started)
            {
            this.setVisible(false);
            if(isServer)
            {
                ServerFrame srvrFrm=new ServerFrame();
                srvrFrm.setVisible(true);
            }
            else{
                
                Client c=new Client();
                c.setVisible(true);
                
                
            }
            started=true;
            }
            
        }
        else if(getCounter()==1000){
            setIcon(image, "Assets/images/youDidIt.png",1400,900);
        }
        else if(getCounter()>=1001){
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton1.setText("Click To Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 780, -1, -1));

        image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageMouseClicked(evt);
            }
        });
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1400, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageMouseClicked
        // TODO add your handling code here:
        setCounter(getCounter() + 1);
       
        accordingToCounter();
    }//GEN-LAST:event_imageMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         setCounter(getCounter() + 1);
        accordingToCounter();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beginning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beginning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the counter
     */
    public int getCounter() {
        return counter;
    }

    /**
     * @param counter the counter to set
     */
    public void setCounter(int counter) {
        this.counter = counter;
        accordingToCounter();
    }
}
