package animalfriendconnector;

import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kingm
 */
public class PicturePanel extends javax.swing.JPanel {

    /**
     * Creates new form PicturePanel
     */
    String selected=null;
    ServerFrame parent;
    int numCorrect=0;
    ArrayList<Animal> animalsList;
    public ServerFrame getParent() {
        return parent;
    }
    

    public void setParent(ServerFrame parent) {
        this.parent = parent;
    }
    public PicturePanel() {
        animalsList = AnimalListCreator.subList(0, 4);
        Collections.shuffle(animalsList);
        
        initComponents();
        setIcon(background,"Assets/images/background1.png",1400,900);
        setIcon(imgButton1,animalsList.get(0).getImageLoc());
        setIcon(imgButton2,animalsList.get(1).getImageLoc());
        setIcon(imgButton3,animalsList.get(2).getImageLoc());
        setIcon(imgButton4,animalsList.get(3).getImageLoc());
        
    }
   
    private void exit()
    {
        Beginning b=new Beginning();
        b.setCounter(1000);
        b.setVisible(true);
        parent.setVisible(false);
    }
    private void setIcon(JButton button, String s)
    {
        setIcon(button, s,200,200);
        button.setSize(200,200);
    
    }
    private void setIcon(JButton button, String s,int w, int h)
    {
        button.setIcon(new ImageIcon(((new ImageIcon(
            s).getImage()
            .getScaledInstance(w, h,
                    java.awt.Image.SCALE_SMOOTH)))));
    }
    private void setIcon(JLabel label, String s,int w, int h)
    {
        label.setIcon(new ImageIcon(((new ImageIcon(
            s).getImage()
            .getScaledInstance(w, h,
                    java.awt.Image.SCALE_SMOOTH)))));
    }
    private void select()
    {
        System.out.println(selected);
        getParent().setSelected(selected);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        imgButton3 = new javax.swing.JButton();
        imgButton1 = new javax.swing.JButton();
        imgButton4 = new javax.swing.JButton();
        imgButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgButton3.setBorder(null);
        imgButton3.setBorderPainted(false);
        imgButton3.setPreferredSize(new java.awt.Dimension(489, 469));
        imgButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgButton3ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(imgButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 200, 200));

        imgButton1.setBorder(null);
        imgButton1.setBorderPainted(false);
        imgButton1.setPreferredSize(new java.awt.Dimension(489, 469));
        imgButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(imgButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 200, 200));

        imgButton4.setBorder(null);
        imgButton4.setBorderPainted(false);
        imgButton4.setPreferredSize(new java.awt.Dimension(489, 469));
        imgButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgButton4ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(imgButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 200, 200));

        imgButton2.setBorder(null);
        imgButton2.setBorderPainted(false);
        imgButton2.setPreferredSize(new java.awt.Dimension(489, 469));
        imgButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(imgButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 200, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("What's the Animal?");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        background.setText("jLabel2");
        jLayeredPane1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imgButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgButton3ActionPerformed
        // TODO add your handling code here:
        selected=animalsList.get(2).getName();
        select();
        try {
            sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(PicturePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(getParent().getServer().getSelectedSound().equalsIgnoreCase(selected)){
            setIcon(imgButton3, "Assets/images/check.png");
            imgButton3.setEnabled(false);
            numCorrect++;
            if(numCorrect==4)
            {
                exit();
            }
        }
        
    }//GEN-LAST:event_imgButton3ActionPerformed

    private void imgButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgButton1ActionPerformed
        // TODO add your handling code here:
        selected=animalsList.get(0).getName();
        select();
        try {
            sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(PicturePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(getParent().getServer().getSelectedSound().equalsIgnoreCase(selected)){
            setIcon(imgButton1, "Assets/images/check.png");
            imgButton1.setEnabled(false);
            numCorrect++;
            if(numCorrect==4)
            {
                exit();
            }
        }
    }//GEN-LAST:event_imgButton1ActionPerformed

    private void imgButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgButton4ActionPerformed
        // TODO add your handling code here:
        selected=animalsList.get(3).getName();
        select();
        try {
            sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(PicturePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(getParent().getServer().getSelectedSound().equalsIgnoreCase(selected)){
            setIcon(imgButton4, "Assets/images/check.png");
            imgButton4.setEnabled(false);
            numCorrect++;
            if(numCorrect==4)
            {
                exit();
            }
        }
    }//GEN-LAST:event_imgButton4ActionPerformed

    private void imgButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgButton2ActionPerformed
        // TODO add your handling code here:
        selected=animalsList.get(1).getName();
        select();
        try {
            sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(PicturePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(getParent().getServer().getSelectedSound().equalsIgnoreCase(selected)){
            setIcon(imgButton2, "Assets/images/check.png");
            imgButton2.setEnabled(false);
            numCorrect++;
            if(numCorrect==4)
            {
                exit();
            }
        }
    }//GEN-LAST:event_imgButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton imgButton1;
    private javax.swing.JButton imgButton2;
    private javax.swing.JButton imgButton3;
    private javax.swing.JButton imgButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
