package animalfriendconnector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author kingm
 */
import java.io.File;
import javax.sound.sampled.*;
import javax.swing.*;
import java.awt.*;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
public class SoundPanel extends javax.swing.JPanel {

    /**
     * Creates new form SoundPanel
     */
    private Client parent;
    private ClientComm comm;
    int numCorrect=0;
    ArrayList<Animal> animalsList;
    public ClientComm getComm() {
        return comm;
    }

    public void setComm(ClientComm comm) {
        this.comm = comm;
    }
    public void setParent(Client c)
    {
        parent=c;
    }
    private void exit()
    {
        Beginning b=new Beginning();
        b.setCounter(1000);
        b.setVisible(true);
        setVisible(false);
        parent.setVisible(false);
    }
    public SoundPanel() {
        initComponents();
        animalsList = AnimalListCreator.subList(0, 4);
        Collections.shuffle(animalsList);
        /*soundButton1.setIcon(new ImageIcon(((new ImageIcon(
            "Assets/images/cat.png").getImage()
            .getScaledInstance(250, 250,
                    java.awt.Image.SCALE_SMOOTH)))));*/
        setIcon(background,"Assets/images/background1.png",1400,900);
        setIcon(soundButton1,"Assets/images/sound1.png");
        setIcon(soundButton2,"Assets/images/sound2.png");
        setIcon(soundButton3,"Assets/images/sound3.png");
        setIcon(soundButton4,"Assets/images/sound4.png");
    }
    private void setIcon(JButton button, String s)
    {
        setIcon(button, s,200,200);
        button.setSize(200,200);
    
    }
    private void setIcon(JButton button, String s,int w, int h)
    {
        button.setIcon(new ImageIcon(((new ImageIcon(
            s).getImage()
            .getScaledInstance(w, h,
                    java.awt.Image.SCALE_SMOOTH)))));
    }
    private void setIcon(JLabel label, String s,int w, int h)
    {
        label.setIcon(new ImageIcon(((new ImageIcon(
            s).getImage()
            .getScaledInstance(w, h,
                    java.awt.Image.SCALE_SMOOTH)))));
    }
    public void playSound(String fileName) {
        
        System.out.println(fileName);
        try {
            File yourFile=new File(fileName);
            AudioInputStream stream;
            AudioFormat format;
            DataLine.Info info;
            Clip clip;

            stream = AudioSystem.getAudioInputStream(yourFile);
            format = stream.getFormat();
            info = new DataLine.Info(Clip.class, format);
            clip = (Clip) AudioSystem.getLine(info);
            clip.open(stream);
            clip.start();
        } catch (Exception e) {
            System.out.print(e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        soundButton1 = new javax.swing.JButton();
        soundButton2 = new javax.swing.JButton();
        soundButton3 = new javax.swing.JButton();
        soundButton4 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1400, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("What's the Animal Sound?");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 474, 136));

        soundButton1.setBorder(null);
        soundButton1.setBorderPainted(false);
        soundButton1.setPreferredSize(new java.awt.Dimension(489, 469));
        soundButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundButton1ActionPerformed(evt);
            }
        });
        add(soundButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 200, 200));

        soundButton2.setBorder(null);
        soundButton2.setBorderPainted(false);
        soundButton2.setPreferredSize(new java.awt.Dimension(489, 469));
        soundButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundButton2ActionPerformed(evt);
            }
        });
        add(soundButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 200, 200));

        soundButton3.setBorder(null);
        soundButton3.setBorderPainted(false);
        soundButton3.setPreferredSize(new java.awt.Dimension(489, 469));
        soundButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundButton3ActionPerformed(evt);
            }
        });
        add(soundButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 200, 200));

        soundButton4.setBorder(null);
        soundButton4.setBorderPainted(false);
        soundButton4.setPreferredSize(new java.awt.Dimension(489, 469));
        soundButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soundButton4ActionPerformed(evt);
            }
        });
        add(soundButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 200, 200));

        background.setText("jLabel2");
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void soundButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundButton2ActionPerformed
        // TODO add your handling code here:
        Animal animal=animalsList.get(1);
        String name=animal.getName();
        playSound(animal.getSoundLoc());
        
        String response=comm.sendMessage(name);
        if(response.equalsIgnoreCase("true")){
            setIcon(soundButton2, "Assets/images/check.png");
            soundButton2.setEnabled(false);
            numCorrect++;
            if(numCorrect==4)
            {
                exit();
            }
        }
    }//GEN-LAST:event_soundButton2ActionPerformed

    private void soundButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundButton3ActionPerformed
        // TODO add your handling code here:
        Animal animal=animalsList.get(2);
        String name=animal.getName();
        playSound(animal.getSoundLoc());
        
        String response=comm.sendMessage(name);
        if(response.equalsIgnoreCase("true")){
            setIcon(soundButton3, "Assets/images/check.png");
            soundButton3.setEnabled(false);
            numCorrect++;
            if(numCorrect==4)
            {
                exit();
            }
        }
        
    }//GEN-LAST:event_soundButton3ActionPerformed

    private void soundButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundButton4ActionPerformed
        // TODO add your handling code here:
        Animal animal=animalsList.get(3);
        String name=animal.getName();
        playSound(animal.getSoundLoc());
        
        String response=comm.sendMessage(name);
        if(response.equalsIgnoreCase("true")){
            setIcon(soundButton4, "Assets/images/check.png");
            soundButton4.setEnabled(false);
            numCorrect++;
            if(numCorrect==4)
            {
                exit();
            }
        }
    }//GEN-LAST:event_soundButton4ActionPerformed

    private void soundButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundButton1ActionPerformed
        // TODO add your handling code here:
        Animal animal=animalsList.get(0);
        String name=animal.getName();
        playSound(animal.getSoundLoc());
        
        String response=comm.sendMessage(name);
        if(response.equalsIgnoreCase("true")){
            setIcon(soundButton1, "Assets/images/check.png");
            soundButton1.setEnabled(false);
            numCorrect++;
            if(numCorrect==4)
            {
                exit();
            }
        }
    }//GEN-LAST:event_soundButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton soundButton1;
    private javax.swing.JButton soundButton2;
    private javax.swing.JButton soundButton3;
    private javax.swing.JButton soundButton4;
    // End of variables declaration//GEN-END:variables
}
